[project]
name = "gojira"
description = "A Telegram bot that retrieves data from the Anilist API, specifically for manga and anime content."
readme = "README.rst"
license = { file="LICENSE" }
requires-python = ">=3.10"
authors = [
    { name = "Hitalo M." },
]
dependencies = [
    "aiogram[fast, i18n] >= 3.0.0b7",
    "tortoise-orm[accel] >= 0.19.0",
    "aiohttp[speedups] >= 3.8.4",
    "bs4 >= 0.0.1",
    "numpy >= 1.24.3",
    "humanize >= 4.6.0",
    "loguru >= 0.7.0",
    "pydantic[dotenv] >= 1.10.7",
]
dynamic = ["version"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "gojira/__init__.py"

[tool.hatch.metadata]
allow-direct-references = true

[project.urls]
Repository = "https://github.com/HitaloM/Gojira/"

[tool.black]
exclude = '''
(
    \.git
  | venv
)
'''

[tool.isort]
profile = "black"

[tool.rye]
managed = true
